### ISSUE TITLE
`plot_edgeevidence` with `split = TRUE` should show figures side by side

### ISSUE THREAD

**Issue by vandenman** [KarolineHuth/easybgm#43]
This code
```r
fit2 <- easybgm(data, type = "ordinal",
               iter = 1000, save = TRUE,
               centrality = TRUE)

rr <- plot_edgeevidence(fit2, split = TRUE)
```
create 2 plots. But the default behavior in RStudio is to show only the last one. 

A user would probably prefer:
```r
layout(t(1:2))
plot_edgeevidence(fit2, split = TRUE)
```

Perhaps add something like
```r
if (split) {

  # get current par settings and reset them at the end of this function
  old_par <- graphics::par(no.readonly = TRUE)
  on.exit(graphics::par(old_par))
  
  # two columns, 1 row
  par(mfrow = c(1, 2))

}
```
in addition:
- The default value for `split` is `split = F`, this should probably be `split = FALSE`. 
- These plot functions create `qgraph` objects. To accommodate more advanced editing by users these could be (invisibly) returned.

**Comment by KarolineHuth** [comment]
Re layout: kept as 1:1, so users are able to extract the plots individually. but added a description on adding a layout argument
Re split: updated as split = FALSE
