### ISSUE TITLE
`plot_posteriorstructure`, `plot_structure`, and `plot_network` seem inconsistent

### ISSUE THREAD

**Issue by vandenman** [KarolineHuth/easybgm#44]
`plot_posteriorstructure` plots the posterior probability of each structure according to some ordering of the possible structures.

`plot_structure` plots a network of some structure, probably the one with the highest posterior probability?

Either way, the naming here is somewhat inconsistent because you'd expect both plots to return more or less the same kind of plot based on them ending in "structure". Perhaps `plot_posteriorstructureprobs` would solve that? 

Finally, `plot_network` shows a network plot with edge labels. `plot_structure`, however, uses numbers (1:p) which seems inconsistent.

Probably obvious, but the documentation could use some more love :wink:

**Comment by KarolineHuth** [comment]
Re naming: adapting to plot_structure_probabilities and also plot_complexity_probabilities
Re edge labeling: already included in developer branch
Re documentation: Improved :)
